package br.com.yuriabe.Bestiario.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;

// this class is an entity, persist data in database
@Entity
// the table associated in database
@Table(name = "jogos")
// encapsulating methods
@Getter
@Setter
// constructor methods
@AllArgsConstructor
@NoArgsConstructor

public class JogoModel {
    // this attribute is an ID
    @Id

    // the value will be generated by auto increment
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    // this attribute is a String, not null and max-length 50
    @NotNull
    @Column(name = "titulo", length = 100, nullable = false)
    private String titulo;

    @Column(name = "genero", length = 50)                                                                           // nulo
    private String genero;
    
    @Column(name = "estudio", length = 100)                                                                           // nulo
    private String estudio;
}