package br.com.yuriabe.Bestiario.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.util.List;

// this class is an entity, persist data in database
@Entity
// the table associated in database
@Table(name = "jogos")
// encapsulating methods
@Getter
@Setter
// constructor methods
@AllArgsConstructor
@NoArgsConstructor

public class JogoModel {
    // this attribute is an ID
    @Id

    // the value will be generated by auto increment
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @NotNull
    @Column(name = "titulo", length = 100, nullable = false)
    private String titulo;

    @Column(name = "genero", length = 50)
    private String genero;

    @Column(name = "estudio", length = 100)
    private String estudio;

    @OneToMany(mappedBy = "jogo")
    private List<InimigoModel> inimigos;
}